name: open-pr-slack-action
description: 'Sends a message showing all open PRs to a given slack channel'
inputs:
  slack-token:
    description: 'Slack token'
    required: true
  slack-channel:
    description: 'Slack channel'
    required: true
runs:
    using: 'composite'
    steps:
      - name: Get all open PRs
        shell: bash
        id: get-open-prs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_LIST=$(gh pr list --json number,title,url,assignees --state OPEN --limit 100 --search 'is:pr is:open draft:false' --repo ${{github.repository}})
          echo "pr-details<<EOF" >> $GITHUB_ENV
          echo "$(echo $PR_LIST | jq -r '.[] | "• \\<\(.url)\\|\(.title)> - by \((.assignees | if . != [] then .[].login else "🫥" end))" | gsub("\\\\";"")' | sed 's/,$//')" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "pr-list=$PR_LIST" >> $GITHUB_OUTPUT

      - name: Get Reviews states for PRs
        shell: bash
        id: get-pr-reviews
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_REVIEWS=$(gh pr list --json number,title,url --state OPEN --limit 100 --search 'is:pr is:open draft:false' --repo ${{github.repository}})    
          echo "PR_REVIEWS looks like this $PR_REVIEWS"
          numbers=$(echo $PR_REVIEWS | jq -r '.[] | .number')
          echo "pr-reviews<<EOF" >> $GITHUB_ENV
          for i in $numbers;
          do
            echo "i is $i"
            title=$(echo "$PR_REVIEWS" | jq --arg i "$i" -r '.[] | select(.number == ($i | tonumber)) | .title')
            echo "title is $title"
            url=$(echo "$PR_REVIEWS" | jq --arg i "$i" -r '.[] | select(.number == ($i | tonumber)) | .url')
            echo "url is $url"
            pr_reviews=$(gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{github.repository}}/pulls/$i/reviews)
            echo "*State for PR <$url|$i> is:*" >> $GITHUB_ENV
            echo "$(echo $pr_reviews | jq -r '.[] | select(.state == "CHANGES_REQUESTED" or .state == "APPROVED") | "• \((if (.state == "APPROVED" ) then "✅" else "❌" end)) \(.state) at \(.submitted_at)" | gsub("\\\\";"")' | sed 's/,$//')" >> $GITHUB_ENV
          done
          echo "EOF" >> $GITHUB_ENV
          

      - name: get amount of all open prs from github
        shell: bash
        id: get-open-prs-amount
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "pr-amount=$(echo '${{steps.get-open-prs.outputs.pr-list}}' | jq length)" >> $GITHUB_OUTPUT

      - name: Send message with PRs to Slack API
        id: notify
        if: ${{ env.pr-details != '' }}
        uses: archive/github-actions-slack@v2.9.0
        with:
          slack-bot-user-oauth-access-token: ${{ inputs.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-blocks: >-
            [
              {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "Open Pull Requests 🫢️‍",
                    "emoji": true
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.get-open-prs-amount.outputs.pr-amount }} pull requests open in <https://github.com/${{ github.repository }}|${{ github.repository }}> 🤓"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.pr-details }}"
                }
              }
            ]

      - name: Send Thread Message
        if: ${{ env.pr-details != ''}}
        uses: archive/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ inputs.slack-token }}
          slack-channel: ${{ fromJson(steps.notify.outputs.slack-result).response.channel }}
          slack-optional-thread_ts: ${{ fromJson(steps.notify.outputs.slack-result).response.message.ts }}
          slack-blocks: >-
            [
              {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.pr-reviews }}"
                }
              }
            ]
  
